version: "2.1"

services:

  postgres:
    #image: healthcheck/postgres:alpine
    build: ./postgres
    ports: ["5432:5432"]
    volumes: ["postgres-data:/var/lib/postgresql/data"]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks: [backing-services]

  rabbitmq:
    build: ./rabbitmq
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
      - "rabbitmq-data:/etc/rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [backing-services]
    restart: unless-stopped

volumes:
  postgres-data: {}
  rabbitmq-data: {}

networks:
  backing-services:
    driver: bridge
