version: "2.1"

services:

  app:
    build: .
    volumes: ["app-data:/home/app"]
    ports: ["8080:8080"]
    restart: unless-stopped
    networks: [backing-services]
    mem_limit: 314572800 # container limit: 350Mb (350 * 1024 * 1024)

volumes:
  app-data: {}

networks:
  backing-services:
    driver: bridge
